In [ ]:
!pip install -q onnxruntime tokenizers huggingface_hub

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.6/23.6 MB 54.5 MB/s eta 0:00:00

In [ ]:
from huggingface_hub import hf_hub_download

MODEL_REPO = "onnx-models/all-MiniLM-L6-v2-onnx"

onnx_model_path = hf_hub_download(
    repo_id=MODEL_REPO,
    filename="model.onnx"
)

tokenizer_path = hf_hub_download(
    repo_id=MODEL_REPO,
    filename="tokenizer.json"
)

print("✅ ONNX model downloaded")
print("✅ Tokenizer downloaded")
print("Model:", onnx_model_path)
print("Tokenizer:", tokenizer_path)

model.onnx: reconstructing file:   0%|          |  0.00B / 90.4MB

model.onnx: downloading bytes:           |  0.00B

tokenizer.json:   0%|          | 0.00/712k [00:00<?, ?B/s]

✅ ONNX model downloaded
✅ Tokenizer downloaded
Model: /root/.cache/huggingface/hub/models--onnx-models--all-MiniLM-L6-v2-onnx/snapshots/75251058ddd779e3a744f87fdf63fb39681aec16/model.onnx
Tokenizer: /root/.cache/huggingface/hub/models--onnx-models--all-MiniLM-L6-v2-onnx/snapshots/75251058ddd779e3a744f87fdf63fb39681aec16/tokenizer.json

In [ ]:
# import onnxruntime as ort

# session = ort.InferenceSession(
#     onnx_model_path,
#     providers=["CPUExecutionProvider"]
# )

# print("Inputs:")
# for x in session.get_inputs():
#     print(
#         x.name,
#         x.shape,
#         x.type
#     )

# print("\nOutputs:")
# for x in session.get_outputs():
#     print(
#         x.name,
#         x.shape,
#         x.type
#     )

In [ ]:
import numpy as np
import onnxruntime as ort
from tokenizers import Tokenizer


class ONNXEmbeddingModel:

    def __init__(
        self,
        model_path,
        tokenizer_path,
        max_length=256
    ):

        self.tokenizer = Tokenizer.from_file(
            tokenizer_path
        )

        self.tokenizer.enable_truncation(
            max_length=max_length
        )

        self.tokenizer.enable_padding()

        self.session = ort.InferenceSession(
            model_path,
            providers=["CPUExecutionProvider"]
        )

    def encode(
        self,
        sentences,
        batch_size=32,
        show_progress_bar=False,
        normalize_embeddings=True
    ):

        if isinstance(sentences, str):
            sentences = [sentences]

        all_embeddings = []

        for start in range(
            0,
            len(sentences),
            batch_size
        ):

            batch = sentences[
                start:start + batch_size
            ]

            encodings = self.tokenizer.encode_batch(
                batch
            )

            input_ids = np.asarray(
                [e.ids for e in encodings],
                dtype=np.int64
            )

            attention_mask = np.asarray(
                [e.attention_mask for e in encodings],
                dtype=np.int64
            )

            token_type_ids = np.asarray(
                [e.type_ids for e in encodings],
                dtype=np.int64
            )

            outputs = self.session.run(
                ["sentence_embedding"],
                {
                    "input_ids": input_ids,
                    "attention_mask": attention_mask,
                    "token_type_ids": token_type_ids
                }
            )

            embeddings = outputs[0].astype(
                np.float32
            )

            if normalize_embeddings:

                norms = np.linalg.norm(
                    embeddings,
                    axis=1,
                    keepdims=True
                )

                embeddings = embeddings / np.clip(
                    norms,
                    1e-12,
                    None
                )

            all_embeddings.append(
                embeddings
            )

        return np.vstack(
            all_embeddings
        )

    def get_sentence_embedding_dimension(self):
        return 384

In [ ]:
# onnx_embedding_model = ONNXEmbeddingModel(
#     onnx_model_path,
#     tokenizer_path
# )

# print("✅ ONNX embedding model loaded!")
# print(
#     "Embedding dimension:",
#     onnx_embedding_model.get_sentence_embedding_dimension()
# )

In [ ]:
!pip install -q pandas numpy scikit-learn
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

print("Libraries imported successfully!")

Libraries imported successfully!

In [ ]:
!pip install -q datasets

In [ ]:
from datasets import load_dataset

dataset = load_dataset(
    "bitext/Bitext-retail-ecommerce-llm-chatbot-training-dataset"
)

print(dataset)

README.md:   0%|          | 0.00/10.1k [00:00<?, ?B/s]

bitext-retail-ecommerce-llm-chatbot-trai(…): reconstructing file:   0%|          |  0.00B / 42.6MB

bitext-retail-ecommerce-llm-chatbot-trai(…): downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/44884 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['instruction', 'intent', 'category', 'tags', 'response'],
        num_rows: 44884
    })
})

In [ ]:
df = dataset["train"].to_pandas()

print("Shape:", df.shape)
print("Columns:")
print(df.columns.tolist())

display(df.head(15))

Shape: (44884, 5)
Columns:
['instruction', 'intent', 'category', 'tags', 'response']

,instruction,intent,category,tags,response
0,I got to add an item to the cart,add_product,CART,BL,I'll get right on it! I'm here to assist you i...
1,wanna add fucking products to the basket can h...,add_product,CART,BCIMQWZ,I sincerely apologize if you've encountered an...
2,i have to add products to the basket i ned help,add_product,CART,BCMQZ,You bet! I'm here to assist you in adding prod...
3,di like to add products to the cart could i ge...,add_product,CART,BCILMPQZ,Indeed! I'm here to assist you in adding produ...
4,"I need to add an item to the cart , where do I...",add_product,CART,BCILZ,I'll take care of it! I'm here to help you wit...
5,help me add products to the basket,add_product,CART,BM,I'm happy to help! I'm here to guide you throu...
6,"I need to add a fucking product to the basket,...",add_product,CART,BCIWZ,"I understand the inconvenience, and I'm sorry ..."
7,"I have to add items to the basket, where could...",add_product,CART,BCILMP,Indeed! I'm here to help you with adding items...
8,I would like to add a fucking item to the bask...,add_product,CART,BCILPWZ,I genuinely apologize for any frustration caus...
9,i got to add a fucking item ot the cart can i ...,add_product,CART,BCILQWZ,I sincerely apologize for any frustration you ...
10,"I want to add fucking items to the basket, how...",add_product,CART,BCILMW,I deeply apologize for the frustration you've ...
11,could i add a product to the basket,add_product,CART,BIPQ,I'll do my best! I'm here to help you add a pr...
12,could I add fucking itmes to the cart?,add_product,CART,BILMPWZ,I'm sorry for any frustration you may have exp...
13,"I need to add a product to the basket, how can...",add_product,CART,BCI,I'm on it! I'm here to assist you in adding a ...
14,need to add items to the baset can uhelp me,add_product,CART,BCILMQZ,Of course! I'm here to assist you with adding ...

In [ ]:
for col in df.columns:
    print("\nCOLUMN:", col)
    print(df[col].dropna().astype(str).iloc[0][:300])

COLUMN: instruction
I got to add an item to the cart

COLUMN: intent
add_product

COLUMN: category
CART

COLUMN: tags
BL

COLUMN: response
I'll get right on it! I'm here to assist you in adding an item to your cart. Here's a step-by-step guide to help you out:

1. Browse through our {{Product Catalog}} to find the item you want to add to your cart.
2. Once you've found the item, click on the "{{Add to Cart}}" button or select the desir

In [ ]:
# 1. Basic information
print("Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

# 2. Number of unique intents and categories
print("\nNumber of unique intents:",
      df["intent"].nunique())

print("Number of unique categories:",
      df["category"].nunique())

# 3. List all intents
print("\nINTENTS:")
print(sorted(df["intent"].unique().tolist()))

# 4. List all categories
print("\nCATEGORIES:")
print(sorted(df["category"].unique().tolist()))

# 5. Missing values
print("\nMISSING VALUES:")
print(df.isnull().sum())

# 6. Duplicate rows
print("\nDuplicate rows:",
      df.duplicated().sum())

# 7. Intent distribution
print("\nINTENT DISTRIBUTION:")
print(
    df["intent"]
    .value_counts()
    .sort_values(ascending=False)
)

# 8. Category distribution
print("\nCATEGORY DISTRIBUTION:")
print(
    df["category"]
    .value_counts()
    .sort_values(ascending=False)
)

Shape: (44884, 5)

Columns:
['instruction', 'intent', 'category', 'tags', 'response']

Number of unique intents: 46
Number of unique categories: 13

INTENTS:
['add_product', 'availability', 'availability_in_store', 'availability_online', 'cancel_order', 'change_account', 'change_order', 'close_account', 'customer_service', 'damaged_delivery', 'delivery_issue', 'delivery_time', 'exchange_product', 'exchange_product_in_store', 'human_agent', 'missing_item', 'open_account', 'order_history', 'pay', 'payment_issue', 'payment_methods', 'product_information', 'product_issue', 'recover_password', 'refund_policy', 'refund_status', 'remove_product', 'request_invoice', 'request_refund', 'request_right_to_rectification', 'return_policy', 'return_product', 'return_product_in_store', 'return_product_online', 'sales_period', 'shipping_costs', 'store_location', 'store_opening_hours', 'submit_feedback', 'submit_product_feedback', 'submit_product_idea', 'technical_issue', 'track_delivery', 'track_order', 'use_app', 'wrong_item']

CATEGORIES:
['ACCOUNT', 'APP_WEBSITE', 'CART', 'CONTACT', 'DELIVERY', 'FEEDBACK', 'ORDER', 'PAYMENT', 'PRODUCT', 'RETURNS', 'SALES', 'STORE', 'USER']

MISSING VALUES:
instruction    0
intent         0
category       0
tags           0
response       0
dtype: int64

Duplicate rows: 0

INTENT DISTRIBUTION:
intent
request_invoice                   1000
refund_status                      999
use_app                            999
payment_issue                      996
cancel_order                       996
delivery_issue                     996
wrong_item                         996
track_delivery                     996
payment_methods                    995
sales_period                       995
close_account                      995
submit_product_idea                995
return_product                     994
return_policy                      994
human_agent                        994
refund_policy                      994
technical_issue                    994
return_product_in_store            994
submit_product_feedback            994
remove_product                     993
return_product_online              993
recover_password                   993
availability_online                993
customer_service                   992
damaged_delivery                   992
store_opening_hours                992
product_issue                      992
submit_feedback                    991
exchange_product_in_store          991
pay                                990
request_right_to_rectification     989
order_history                      988
exchange_product                   988
track_order                        988
product_information                987
change_account                     987
open_account                       987
shipping_costs                     974
availability                       972
change_order                       961
add_product                        957
request_refund                     957
store_location                     924
delivery_time                      920
availability_in_store              756
missing_item                       721
Name: count, dtype: int64

CATEGORY DISTRIBUTION:
category
RETURNS        6925
PRODUCT        6679
DELIVERY       6595
ACCOUNT        4950
ORDER          3945
PAYMENT        2981
FEEDBACK       2980
APP_WEBSITE    1993
CONTACT        1986
CART           1950
STORE          1916
SALES           995
USER            989
Name: count, dtype: int64

In [ ]:
# Show 5 examples for every intent

examples = (
    df.groupby("intent", group_keys=False)
      .head(5)
      [["instruction", "intent", "category"]]
)

display(examples)

,instruction,intent,category
0,I got to add an item to the cart,add_product,CART
1,wanna add fucking products to the basket can h...,add_product,CART
2,i have to add products to the basket i ned help,add_product,CART
3,di like to add products to the cart could i ge...,add_product,CART
4,"I need to add an item to the cart , where do I...",add_product,CART
...,...,...,...
43888,"I got a fucking product in the wrong color , c...",wrong_item,DELIVERY
43889,some items in my delivery are incorrect can uh...,wrong_item,DELIVERY
43890,fucking products in my delivery are wrong i ne...,wrong_item,DELIVERY
43891,"the fucking items I ordered are incorrect, can...",wrong_item,DELIVERY
43892,fucking products are incorrect how do i repor...,wrong_item,DELIVERY

In [ ]:
print("Rows:", len(df))
print("Intents:", df["intent"].nunique())
print("Categories:", df["category"].nunique())

print("\nIntent examples:")
display(
    df[["instruction", "intent", "category", "response"]].sample(
        10,
        random_state=42
    )
)

Rows: 44884
Intents: 46
Categories: 13

Intent examples:

,instruction,intent,category,response
33698,"I'd like information about the fucking sales, ...",sales_period,SALES,I genuinely apologize for the inappropriate la...
44212,one of the products in mh package is incorrect...,wrong_item,DELIVERY,I'm sorry to hear that you received an incorre...
14749,im missing some fucking products i ordered how...,missing_item,DELIVERY,"We regret the inconvenience, and we're sorry f..."
36515,im looking for information aboyt ur fucking sh...,store_opening_hours,STORE,I genuinely apologize for any frustration caus...
24333,I'd like information about the fucking status ...,refund_status,RETURNS,I sincerely apologize for the inconvenience an...
29325,I'd like information about your fucking return...,return_policy,RETURNS,We recognize the inconvenience and apologize f...
5770,i boughty a product but i chose a wrong model ...,change_order,ORDER,Our apologies for any inconvenience caused by ...
16295,I'd like to review my purchase history how cou...,order_history,ACCOUNT,Definitely! I can help you with that. Reviewin...
26125,i have to download a fucking invoice could i g...,request_invoice,ORDER,I deeply apologize for any frustration or inco...
7707,can ya help me calling fucking customer support,customer_service,CONTACT,I am truly sorry to hear about the frustration...

In [ ]:
print(
    df.groupby("intent")["instruction"]
      .count()
      .sort_values()
)

intent
missing_item                       721
availability_in_store              756
delivery_time                      920
store_location                     924
request_refund                     957
add_product                        957
change_order                       961
availability                       972
shipping_costs                     974
product_information                987
open_account                       987
change_account                     987
order_history                      988
track_order                        988
exchange_product                   988
request_right_to_rectification     989
pay                                990
submit_feedback                    991
exchange_product_in_store          991
store_opening_hours                992
product_issue                      992
damaged_delivery                   992
customer_service                   992
remove_product                     993
availability_online                993
recover_password                   993
return_product_online              993
submit_product_feedback            994
refund_policy                      994
return_product                     994
return_policy                      994
human_agent                        994
technical_issue                    994
return_product_in_store            994
submit_product_idea                995
sales_period                       995
payment_methods                    995
close_account                      995
cancel_order                       996
delivery_issue                     996
wrong_item                         996
track_delivery                     996
payment_issue                      996
refund_status                      999
use_app                            999
request_invoice                   1000
Name: instruction, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

X = df["instruction"]
y = df["intent"]

# 80% train, 20% temporary
X_train, X_temp, y_train, y_temp = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

# Split remaining 20% into 10% validation and 10% test
X_val, X_test, y_val, y_test = train_test_split(
    X_temp,
    y_temp,
    test_size=0.50,
    random_state=42,
    stratify=y_temp
)

print("Training:", len(X_train))
print("Validation:", len(X_val))
print("Testing:", len(X_test))

Training: 35907
Validation: 4488
Testing: 4489

In [ ]:
print("Train intents:", y_train.nunique())
print("Validation intents:", y_val.nunique())
print("Test intents:", y_test.nunique())

Train intents: 46
Validation intents: 46
Test intents: 46

In [ ]:
print("\nExample training rows:")
display(
    pd.DataFrame({
        "instruction": X_train.head(10).values,
        "intent": y_train.head(10).values
    })
)

Example training rows:

                                         instruction           intent
0  I have to check your fucking return policy, ho...    return_policy
1  how to report fucking delivery problems with m...   delivery_issue
2  I'd like to pay with  a fucking debit card, wh...  payment_methods
3    idont need my fucking profile i wanna delete it    close_account
4        can you help me to review my order history?    order_history
5  i cant make payments i need assistance repofti...    payment_issue
6  I'd like to send fucking feedback about your c...  submit_feedback
7  I need to seeitem availability, could you help...     availability
8  the app doesnt work on my cell phone could uhe...  technical_issue
9               need to see ur fucking refund policy    refund_policy

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

# Create TF-IDF features
vectorizer = TfidfVectorizer(
    lowercase=True,
    ngram_range=(1, 2),
    min_df=2,
    max_df=0.95,
    sublinear_tf=True
)

X_train_tfidf = vectorizer.fit_transform(X_train)

X_val_tfidf = vectorizer.transform(X_val)
X_test_tfidf = vectorizer.transform(X_test)

print("Train TF-IDF shape:", X_train_tfidf.shape)
print("Validation TF-IDF shape:", X_val_tfidf.shape)
print("Test TF-IDF shape:", X_test_tfidf.shape)

Train TF-IDF shape: (35907, 9048)
Validation TF-IDF shape: (4488, 9048)
Test TF-IDF shape: (4489, 9048)

In [ ]:
classifier = LogisticRegression(
    max_iter=1000,
    random_state=42
)

classifier.fit(
    X_train_tfidf,
    y_train
)

print("Baseline classifier trained successfully!")

Baseline classifier trained successfully!

In [ ]:
from sklearn.metrics import (
    accuracy_score,
    precision_recall_fscore_support,
    classification_report
)

# Validation predictions
val_predictions = classifier.predict(X_val_tfidf)

val_accuracy = accuracy_score(
    y_val,
    val_predictions
)

precision, recall, f1, _ = precision_recall_fscore_support(
    y_val,
    val_predictions,
    average="macro",
    zero_division=0
)

print("Validation Accuracy :", round(val_accuracy, 4))
print("Validation Precision:", round(precision, 4))
print("Validation Recall   :", round(recall, 4))
print("Validation Macro-F1  :", round(f1, 4))

Validation Accuracy : 0.9873
Validation Precision: 0.9876
Validation Recall   : 0.9874
Validation Macro-F1  : 0.9874

In [ ]:
# Final evaluation on the untouched test set

test_predictions = classifier.predict(X_test_tfidf)

test_accuracy = accuracy_score(
    y_test,
    test_predictions
)

test_precision, test_recall, test_f1, _ = (
    precision_recall_fscore_support(
        y_test,
        test_predictions,
        average="macro",
        zero_division=0
    )
)

print("TEST RESULTS")
print("------------------------------")
print("Accuracy :", round(test_accuracy, 4))
print("Precision:", round(test_precision, 4))
print("Recall   :", round(test_recall, 4))
print("Macro-F1 :", round(test_f1, 4))

TEST RESULTS
------------------------------
Accuracy : 0.9851
Precision: 0.9858
Recall   : 0.9853
Macro-F1 : 0.9852

In [ ]:
print(
    classification_report(
        y_test,
        test_predictions,
        zero_division=0
    )
)

                                precision    recall  f1-score   support

                   add_product       1.00      1.00      1.00        95
                  availability       0.98      0.99      0.98        97
         availability_in_store       0.99      0.99      0.99        75
           availability_online       0.99      1.00      1.00       100
                  cancel_order       1.00      0.98      0.99       100
                change_account       0.97      1.00      0.98        98
                  change_order       0.99      1.00      0.99        96
                 close_account       1.00      0.97      0.98       100
              customer_service       1.00      0.99      0.99        99
              damaged_delivery       0.99      0.96      0.97        99
                delivery_issue       1.00      0.99      0.99       100
                 delivery_time       1.00      1.00      1.00        92
              exchange_product       1.00      1.00      1.00        99
     exchange_product_in_store       1.00      0.97      0.98        99
                   human_agent       0.99      1.00      1.00       100
                  missing_item       1.00      1.00      1.00        72
                  open_account       1.00      0.98      0.99        98
                 order_history       1.00      1.00      1.00        99
                           pay       0.97      0.99      0.98        99
                 payment_issue       0.99      1.00      1.00       100
               payment_methods       1.00      0.99      0.99        99
           product_information       0.97      0.99      0.98        98
                 product_issue       0.98      0.99      0.99       100
              recover_password       1.00      1.00      1.00        99
                 refund_policy       0.98      0.98      0.98        99
                 refund_status       0.98      0.94      0.96       100
                remove_product       1.00      1.00      1.00       100
               request_invoice       1.00      0.96      0.98       100
                request_refund       0.95      1.00      0.97        95
request_right_to_rectification       1.00      1.00      1.00        99
                 return_policy       0.97      0.96      0.96       100
                return_product       0.99      0.97      0.98       100
       return_product_in_store       0.97      0.99      0.98       100
         return_product_online       0.98      0.98      0.98        99
                  sales_period       0.99      1.00      0.99        99
                shipping_costs       1.00      0.98      0.99        97
                store_location       0.99      1.00      0.99        92
           store_opening_hours       1.00      1.00      1.00        99
               submit_feedback       0.97      0.98      0.97        99
       submit_product_feedback       0.95      0.98      0.97       100
           submit_product_idea       0.99      0.97      0.98        99
               technical_issue       1.00      1.00      1.00       100
                track_delivery       0.88      1.00      0.93       100
                   track_order       1.00      0.87      0.93        99
                       use_app       1.00      1.00      1.00       100
                    wrong_item       0.95      0.99      0.97       100

                      accuracy                           0.99      4489
                     macro avg       0.99      0.99      0.99      4489
                  weighted avg       0.99      0.99      0.99      4489

In [ ]:
embedding_model = ONNXEmbeddingModel(
    onnx_model_path,
    tokenizer_path
)

print("✅ ONNX embedding model loaded!")
print(
    "Embedding dimension:",
    embedding_model.get_sentence_embedding_dimension()
)

✅ ONNX embedding model loaded!
Embedding dimension: 384

In [ ]:
X_train_embeddings = embedding_model.encode(
    X_train.tolist(),
    batch_size=64,
    show_progress_bar=True,
    normalize_embeddings=True
)

print("Embedding shape:", X_train_embeddings.shape)

Embedding shape: (35907, 384)

In [ ]:
from sklearn.linear_model import LogisticRegression

embedding_classifier = LogisticRegression(
    max_iter=1000,
    random_state=42
)

embedding_classifier.fit(
    X_train_embeddings,
    y_train
)

print("Embedding classifier trained successfully!")

Embedding classifier trained successfully!

In [ ]:
X_val_embeddings = embedding_model.encode(
    X_val.tolist(),
    batch_size=64,
    show_progress_bar=True,
    normalize_embeddings=True
)

print(
    "Validation embedding shape:",
    X_val_embeddings.shape
)

Validation embedding shape: (4488, 384)

In [ ]:
embedding_val_predictions = embedding_classifier.predict(
    X_val_embeddings
)

embedding_val_accuracy = accuracy_score(
    y_val,
    embedding_val_predictions
)

embedding_val_precision, embedding_val_recall, embedding_val_f1, _ = (
    precision_recall_fscore_support(
        y_val,
        embedding_val_predictions,
        average="macro",
        zero_division=0
    )
)

print("EMBEDDING MODEL — VALIDATION")
print("--------------------------------")
print("Accuracy :", round(embedding_val_accuracy, 4))
print("Precision:", round(embedding_val_precision, 4))
print("Recall   :", round(embedding_val_recall, 4))
print("Macro-F1 :", round(embedding_val_f1, 4))

EMBEDDING MODEL — VALIDATION
--------------------------------
Accuracy : 0.9898
Precision: 0.99
Recall   : 0.9895
Macro-F1 : 0.9896

In [ ]:
# Create test embeddings
X_test_embeddings = embedding_model.encode(
    X_test.tolist(),
    batch_size=64,
    show_progress_bar=True,
    normalize_embeddings=True
)

print(
    "Test embedding shape:",
    X_test_embeddings.shape
)

Test embedding shape: (4489, 384)

In [ ]:
# Final evaluation of embedding classifier
embedding_test_predictions = embedding_classifier.predict(
    X_test_embeddings
)

embedding_test_accuracy = accuracy_score(
    y_test,
    embedding_test_predictions
)

embedding_test_precision, embedding_test_recall, embedding_test_f1, _ = (
    precision_recall_fscore_support(
        y_test,
        embedding_test_predictions,
        average="macro",
        zero_division=0
    )
)

print("EMBEDDING MODEL — TEST")
print("--------------------------------")
print("Accuracy :", round(embedding_test_accuracy, 4))
print("Precision:", round(embedding_test_precision, 4))
print("Recall   :", round(embedding_test_recall, 4))
print("Macro-F1 :", round(embedding_test_f1, 4))

EMBEDDING MODEL — TEST
--------------------------------
Accuracy : 0.9866
Precision: 0.9871
Recall   : 0.9869
Macro-F1 : 0.9868

In [ ]:
from sklearn.metrics import confusion_matrix
import pandas as pd
import numpy as np

cm_embedding = confusion_matrix(
    y_test,
    embedding_test_predictions,
    labels=embedding_classifier.classes_
)

embedding_errors = []

for i, true_label in enumerate(
    embedding_classifier.classes_
):
    for j, predicted_label in enumerate(
        embedding_classifier.classes_
    ):

        if i != j and cm_embedding[i, j] > 0:

            embedding_errors.append({
                "true_intent": true_label,
                "predicted_intent": predicted_label,
                "errors": int(cm_embedding[i, j])
            })

embedding_errors_df = (
    pd.DataFrame(embedding_errors)
      .sort_values("errors", ascending=False)
)

display(embedding_errors_df.head(20))

         true_intent       predicted_intent  errors
35       track_order         track_delivery       7
8   damaged_delivery             wrong_item       5
24     return_policy  return_product_online       4
14     refund_policy          return_policy       3
2       cancel_order  return_product_online       2
5     change_account           open_account       2
26    return_product          return_policy       2
19    request_refund                    pay       2
33       track_order          delivery_time       2
17   request_invoice                    pay       2
6      close_account         change_account       1
0       cancel_order    product_information       1
4     change_account          close_account       1
3       cancel_order            track_order       1
1       cancel_order         return_product       1
13     product_issue             wrong_item       1
12   payment_methods                    pay       1
16     refund_status         track_delivery       1
15     refund_status          refund_policy       1
10               pay                use_app       1

In [ ]:
# retrieval_df = df[
#     ["instruction", "intent", "category", "response"]
# ].copy()

# retrieval_df = retrieval_df.reset_index(drop=True)

# print("Retrieval rows:", len(retrieval_df))
# display(retrieval_df.head())

In [ ]:
# retrieval_embeddings = embedding_model.encode(
#     retrieval_df["instruction"].tolist(),
#     batch_size=64,
#     show_progress_bar=True,
#     normalize_embeddings=True
# )

# print("Retrieval embedding shape:")
# print(retrieval_embeddings.shape)

In [ ]:
# from sklearn.metrics.pairwise import cosine_similarity
# import numpy as np

# def semantic_search(query, top_k=5):

#     query_embedding = embedding_model.encode(
#         [query],
#         normalize_embeddings=True
#     )

#     similarities = cosine_similarity(
#         query_embedding,
#         retrieval_embeddings
#     )[0]

#     top_indices = np.argsort(
#         similarities
#     )[::-1][:top_k]

#     results = retrieval_df.iloc[
#         top_indices
#     ].copy()

#     results["similarity"] = similarities[
#         top_indices
#     ]

#     return results[
#         [
#             "instruction",
#             "intent",
#             "category",
#             "response",
#             "similarity"
#         ]
#     ].reset_index(drop=True)

In [ ]:
# queries = [
#     "Where is my order?",
#     "My package has not arrived yet",
#     "I want to return something",
#     "My card payment was declined",
#     "Where is my refund?",
#     "I received the wrong item"
# ]

# for query in queries:

#     print("\n" + "=" * 80)
#     print("QUERY:", query)

#     results = semantic_search(
#         query,
#         top_k=3
#     )

#     display(results)

In [ ]:
# Build retrieval corpus using TRAINING data only

retrieval_train_df = df.loc[
    X_train.index,
    ["instruction", "intent", "category", "response"]
].copy().reset_index(drop=True)

print("Retrieval corpus size:", len(retrieval_train_df))
display(retrieval_train_df.head())

Retrieval corpus size: 35907

,instruction,intent,category,response
0,"I have to check your fucking return policy, ho...",return_policy,RETURNS,I genuinely apologize for any frustration or i...
1,how to report fucking delivery problems with m...,delivery_issue,DELIVERY,"It's our responsibility, and we're sorry for a..."
2,"I'd like to pay with a fucking debit card, wh...",payment_methods,PAYMENT,I sincerely apologize for any previous inconve...
3,idont need my fucking profile i wanna delete it,close_account,ACCOUNT,I sincerely apologize for any frustration or i...
4,can you help me to review my order history?,order_history,ACCOUNT,I'll do my best! I'm here to assist you with r...

In [ ]:
retrieval_train_embeddings = embedding_model.encode(
    retrieval_train_df["instruction"].tolist(),
    batch_size=64,
    show_progress_bar=True,
    normalize_embeddings=True
)

print(
    "Retrieval embedding shape:",
    retrieval_train_embeddings.shape
)

Retrieval embedding shape: (35907, 384)

In [ ]:
def semantic_search(
    query,
    top_k=5
):

    query_embedding = embedding_model.encode(
        [query],
        normalize_embeddings=True
    )

    similarities = cosine_similarity(
        query_embedding,
        retrieval_train_embeddings
    )[0]

    top_indices = np.argsort(
        similarities
    )[::-1][:top_k]

    results = retrieval_train_df.iloc[
        top_indices
    ].copy()

    results["similarity"] = similarities[
        top_indices
    ]

    return results[
        [
            "instruction",
            "intent",
            "category",
            "response",
            "similarity"
        ]
    ].reset_index(drop=True)

In [ ]:
queries = [
    "Where is my order?",
    "My package has not arrived yet",
    "I want to return something",
    "My card payment was declined",
    "Where is my refund?",
    "I received the wrong item"
]

for query in queries:

    print("\n" + "=" * 80)
    print("QUERY:", query)

    results = semantic_search(
        query,
        top_k=3
    )

    display(results)

================================================================================
QUERY: Where is my order?

,instruction,intent,category,response,similarity
0,"I got to see where my order is, where could I ...",track_order,ORDER,I'll do my best! I'd be happy to help you trac...,0.906439
1,"I have to see where my order is , could you he...",track_order,ORDER,I'll do my best! I'd be happy to assist you in...,0.879740
2,"I got to check where my order is, could you he...",track_order,ORDER,I'll take care of it! I'm here to assist you i...,0.874632

================================================================================
QUERY: My package has not arrived yet

,instruction,intent,category,response,similarity
0,i have not received my package could ya help m...,delivery_issue,DELIVERY,I'm genuinely sorry for any inconvenience caus...,0.753894
1,i have not received my package i have to repor...,delivery_issue,DELIVERY,I understand your frustration and apologize fo...,0.748325
2,"I haven't received my package, can you help me...",delivery_issue,DELIVERY,I'm sorry to hear that you haven't received yo...,0.737631

================================================================================
QUERY: I want to return something

,instruction,intent,category,response,similarity
0,"I would like to return an item, help me",return_product,RETURNS,I'm sorry to hear that you would like to retur...,0.895247
1,"I would like to return an item, help me",return_product,RETURNS,We're here to help to us regarding your return...,0.895247
2,"I want to return an item, how do I do it?",return_product,RETURNS,Indeed! I'm here to guide you through the retu...,0.879062

================================================================================
QUERY: My card payment was declined

,instruction,intent,category,response,similarity
0,"my card was declined, can you help me notifing...",payment_issue,PAYMENT,I'm sorry to hear that your card was declined ...,0.903879
1,"my credit card was declined, could you help me...",payment_issue,PAYMENT,I'm sorry to hear that your credit card was de...,0.900309
2,"my card was declined, help me to notify of pay...",payment_issue,PAYMENT,I feel the need to apologize for the inconveni...,0.895796

================================================================================
QUERY: Where is my refund?

,instruction,intent,category,response,similarity
0,where do i get a refund,request_refund,RETURNS,I'm sorry to hear that you're looking for a re...,0.902268
1,where to get a refund,request_refund,RETURNS,I appreciate that you're interested in knowing...,0.886556
2,"I got to see the status of my refund, where ca...",refund_status,RETURNS,I understand how important it is for you to tr...,0.874769

================================================================================
QUERY: I received the wrong item

,instruction,intent,category,response,similarity
0,the fucking item i received is wrong,wrong_item,DELIVERY,I genuinely apologize for the inconvenience ca...,0.834476
1,"the item I received is incorrect, can you help...",wrong_item,DELIVERY,I'm sorry to hear that you received the incorr...,0.774932
2,the fucking item i received is incorrect help ...,wrong_item,DELIVERY,I genuinely apologize for the inconvenience ca...,0.774275

In [ ]:
def retrieval_recall_at_k(
    k=5,
    max_queries=None
):

    # Optionally evaluate a subset for speed
    test_indices = np.arange(len(X_test))

    if max_queries is not None:
        test_indices = test_indices[:max_queries]

    hits = 0
    total = len(test_indices)

    for i in test_indices:

        query = X_test.iloc[i]
        true_intent = y_test.iloc[i]

        query_embedding = embedding_model.encode(
            [query],
            normalize_embeddings=True
        )

        similarities = cosine_similarity(
            query_embedding,
            retrieval_train_embeddings
        )[0]

        top_indices = np.argsort(
            similarities
        )[::-1][:k]

        retrieved_intents = (
            retrieval_train_df
            .iloc[top_indices]["intent"]
            .tolist()
        )

        if true_intent in retrieved_intents:
            hits += 1

    return hits / total

In [ ]:
recall_1 = retrieval_recall_at_k(
    k=1,
    max_queries=None
)

print("Retrieval evaluation on full test set")
print("-------------------------------------")
print("Recall@1:", round(recall_1, 4))

Retrieval evaluation on full test set
-------------------------------------
Recall@1: 0.9844

In [ ]:
# recall_1 = retrieval_recall_at_k(
#     k=1,
#     max_queries=500
# )

# recall_3 = retrieval_recall_at_k(
#     k=3,
#     max_queries=500
# )

# recall_5 = retrieval_recall_at_k(
#     k=5,
#     max_queries=500
# )

# print("Retrieval evaluation on 500 test queries")
# print("----------------------------------------")
# print("Recall@1:", round(recall_1, 4))
# print("Recall@3:", round(recall_3, 4))
# print("Recall@5:", round(recall_5, 4))

In [ ]:
def retrieval_mrr(
    max_queries=None
):
    test_indices = np.arange(len(X_test))

    if max_queries is not None:
        test_indices = test_indices[:max_queries]

    reciprocal_ranks = []

    for i in test_indices:

        query = X_test.iloc[i]
        true_intent = y_test.iloc[i]

        query_embedding = embedding_model.encode(
            [query],
            normalize_embeddings=True
        )

        similarities = cosine_similarity(
            query_embedding,
            retrieval_train_embeddings
        )[0]

        ranked_indices = np.argsort(
            similarities
        )[::-1]

        ranked_intents = (
            retrieval_train_df
            .iloc[ranked_indices]["intent"]
            .tolist()
        )

        # Find first occurrence of correct intent
        rank = None

        for position, intent in enumerate(
            ranked_intents,
            start=1
        ):
            if intent == true_intent:
                rank = position
                break

        if rank is not None:
            reciprocal_ranks.append(
                1 / rank
            )
        else:
            reciprocal_ranks.append(0)

    return np.mean(reciprocal_ranks)

In [ ]:
mrr = retrieval_mrr(
    max_queries=500
)

print("MRR:", round(mrr, 4))

MRR: 0.9973

In [ ]:
unseen_queries = [
    ("Where can I see my shipment?", "track_delivery"),
    ("Can you tell me the status of my order?", "track_order"),
    ("My money hasn't come back yet", "refund_status"),
    ("I was charged but my payment failed", "payment_issue"),
    ("The thing delivered to me is not the one I bought", "wrong_item"),
    ("The product arrived broken", "damaged_delivery"),
    ("How do I send something back?", "return_product"),
    ("Can I return this through the website?", "return_product_online"),
    ("Can I swap this item in a physical shop?", "exchange_product_in_store"),
    ("I want to close my account", "close_account"),
]

In [ ]:
for query, expected_intent in unseen_queries:

    results = semantic_search(
        query,
        top_k=3
    )

    predicted_intent = results.iloc[0]["intent"]

    print("\n" + "=" * 70)
    print("Query   :", query)
    print("Expected:", expected_intent)
    print("Top 1   :", predicted_intent)
    print("Score   :", round(
        results.iloc[0]["similarity"], 4
    ))

    print("\nTop 3 intents:")
    print(
        results[
            ["intent", "similarity"]
        ].to_string(index=False)
    )

======================================================================
Query   : Where can I see my shipment?
Expected: track_delivery
Top 1   : track_delivery
Score   : 0.943

Top 3 intents:
        intent  similarity
track_delivery    0.943038
   track_order    0.907128
track_delivery    0.900857

======================================================================
Query   : Can you tell me the status of my order?
Expected: track_order
Top 1   : track_delivery
Score   : 0.7792

Top 3 intents:
        intent  similarity
track_delivery    0.779194
   track_order    0.722269
   track_order    0.708211

======================================================================
Query   : My money hasn't come back yet
Expected: refund_status
Top 1   : refund_policy
Score   : 0.6568

Top 3 intents:
       intent  similarity
refund_policy    0.656777
refund_policy    0.652071
refund_policy    0.651105

======================================================================
Query   : I was charged but my payment failed
Expected: payment_issue
Top 1   : payment_issue
Score   : 0.8862

Top 3 intents:
       intent  similarity
payment_issue    0.886216
payment_issue    0.837583
payment_issue    0.833485

======================================================================
Query   : The thing delivered to me is not the one I bought
Expected: wrong_item
Top 1   : wrong_item
Score   : 0.6127

Top 3 intents:
    intent  similarity
wrong_item    0.612706
wrong_item    0.587461
wrong_item    0.579456

======================================================================
Query   : The product arrived broken
Expected: damaged_delivery
Top 1   : damaged_delivery
Score   : 0.7281

Top 3 intents:
          intent  similarity
damaged_delivery    0.728080
damaged_delivery    0.720380
damaged_delivery    0.716965

======================================================================
Query   : How do I send something back?
Expected: return_product
Top 1   : return_product
Score   : 0.9096

Top 3 intents:
        intent  similarity
return_product    0.909631
return_product    0.896347
return_product    0.890536

======================================================================
Query   : Can I return this through the website?
Expected: return_product_online
Top 1   : return_policy
Score   : 0.8373

Top 3 intents:
       intent  similarity
return_policy    0.837314
return_policy    0.827048
return_policy    0.806865

======================================================================
Query   : Can I swap this item in a physical shop?
Expected: exchange_product_in_store
Top 1   : exchange_product
Score   : 0.61

Top 3 intents:
                   intent  similarity
         exchange_product    0.610026
exchange_product_in_store    0.607705
exchange_product_in_store    0.604192

======================================================================
Query   : I want to close my account
Expected: close_account
Top 1   : close_account
Score   : 0.9573

Top 3 intents:
       intent  similarity
close_account    0.957258
close_account    0.957224
close_account    0.949676

In [ ]:
def get_answer(query, top_k=3):
    results = semantic_search(
        query,
        top_k=top_k
    )

    best_result = results.iloc[0]

    return {
        "answer": best_result["response"],
        "intent": best_result["intent"],
        "category": best_result["category"],
        "similarity": float(best_result["similarity"])
    }

In [ ]:
query = "Where is my order?"

result = get_answer(query)

print("Customer:", query)
print("Answer:", result["answer"])

Customer: Where is my order?
Answer: I'll do my best! I'd be happy to help you track your order. To check the status of your order, you can follow these steps:

1. Visit our website at {{Company Website URL}}.
2. Log in to your account using your registered email address and password.
3. Navigate to the "{{Order History}}" or "{{My Orders}}" section.
4. Look for the specific order you want to track and click on it.
5. You should be able to see the current status of your order, such as "Processing," "Shipped," or "Delivered," along with any tracking information available.

If you're unable to find the information you need or have any other questions, feel free to reach out to our customer support team at {{Customer Support Phone Number}} or via live chat on our website. We're here to assist you every step of the way!

In [ ]:
test_queries = [
    "Where is my order?",
    "My card payment was declined",
    "I want to return an item",
    "Where is my refund?",
    "I received the wrong product",
    "Can I exchange an item in store?"
]

for query in test_queries:

    result = get_answer(query)

    print("\n" + "=" * 80)
    print("Customer:", query)
    print("Answer:", result["answer"])

================================================================================
Customer: Where is my order?
Answer: I'll do my best! I'd be happy to help you track your order. To check the status of your order, you can follow these steps:

1. Visit our website at {{Company Website URL}}.
2. Log in to your account using your registered email address and password.
3. Navigate to the "{{Order History}}" or "{{My Orders}}" section.
4. Look for the specific order you want to track and click on it.
5. You should be able to see the current status of your order, such as "Processing," "Shipped," or "Delivered," along with any tracking information available.

If you're unable to find the information you need or have any other questions, feel free to reach out to our customer support team at {{Customer Support Phone Number}} or via live chat on our website. We're here to assist you every step of the way!

================================================================================
Customer: My card payment was declined
Answer: I'm sorry to hear that your card was declined and you're experiencing payment problems. I'll do my best to assist you with resolving this issue.

To report a payment problem, please follow these steps:

1. Double-check the card details: Ensure that the card number, expiration date, CVV, and billing address entered are correct. Sometimes, a small error can lead to a declined payment.

2. Verify sufficient funds: Make sure that you have enough funds available in your account to cover the transaction. Insufficient funds can result in a declined payment.

3. Contact your card issuer: If you've confirmed that the card details are accurate and you have enough funds, the next step is to reach out to your card issuer. They can provide insights into why the payment was declined and help resolve any issues.

4. Notify the merchant: If the payment was declined during a specific transaction, it's a good idea to contact the merchant directly. They may be able to provide further assistance or offer alternative payment methods.

5. Monitor your account: Keep an eye on your bank or credit card account to ensure that no unauthorized charges have been made.

If you continue to experience difficulties, please provide more specific information about the payment problem, such as the merchant's name, transaction details, or any error messages you encountered. This will help me assist you further.

Please remember that I'm here to support you throughout this process.

================================================================================
Customer: I want to return an item
Answer: I'll make it happen! I'm here to assist you with that. Returning an item is a simple process. Here's what you need to do:

1. Visit our {{Returns & Exchanges}} page on our website.
2. Look for the option to initiate a return or exchange. It's usually labeled as "{{Start Return}}" or something similar.
3. Provide the requested information, such as your {{Order Number}} or {{Email Address}}, to locate your order.
4. Select the item you wish to return from your order.
5. Choose the reason for the return from the available options.
6. Follow the provided instructions to generate and print the return label.
7. Carefully package the item, including all original accessories and packaging.
8. Attach the return label to the package and make sure it's securely sealed.
9. Drop off the package at your nearest {{Carrier}} location or schedule a pickup.

Once we receive your returned item, we'll initiate the refund process. Please note that it may take some time for the refund to reflect on your original payment method.

If you have any specific questions or encounter any difficulties during the return process, don't hesitate to reach out to our {{Customer Support}} team. We're here to assist you every step of the way.

================================================================================
Customer: Where is my refund?
Answer: I'm sorry to hear that you're looking for a refund. I can definitely assist you with that. Here's what you need to do to get a refund:

1. Contact our customer support team at {{Customer Support Phone Number}} or via email at {{Customer Support Email Address}}.
2. Explain the reason for your refund request and provide any necessary details such as your order number and purchase date.
3. Our customer support team will guide you through the refund process and assist you with the necessary steps.
4. Depending on the payment method you used for your purchase, the refund will be processed accordingly.
5. If you have any further questions or concerns regarding the refund, feel free to reach out to our customer support team.

We apologize for any inconvenience you may have experienced and appreciate your understanding.

================================================================================
Customer: I received the wrong product
Answer: I'm sorry to hear that you received the wrong product in your order. I completely understand how frustrating that can be. Let's get this sorted out for you. To resolve the issue, please follow these steps:

1. Take note of your {{Order Number}}. You may find it in your order confirmation email or on the packing slip.
2. Contact our customer support team through Live Chat on our website at {{Company Website URL}} or call {{Customer Support Phone Number}} during {{Customer Support Working Hours}}.
3. Provide them with your order number and explain the situation. Our team will guide you further to arrange for a return or exchange.
4. If necessary, they will assist you in arranging for a pickup of the wrong item and the delivery of the correct product.

We apologize for any inconvenience caused, and we'll do our best to rectify the situation promptly. If you have any other concerns or questions, please let me know.

================================================================================
Customer: Can I exchange an item in store?
Answer: I'm on it! You can definitely exchange an item in-store. We're here to assist you with that. When you visit our store, just bring the item you wish to exchange along with the original receipt or proof of purchase. Our friendly staff will be more than happy to help you find a suitable replacement or assist you with store credit. If you have any other questions or need further assistance, feel free to let us know. We're here to make your exchange experience as smooth as possible!

In [ ]:
def chatbot(user_input, top_k=1, threshold=0.55):

    # Semantic retrieval
    results = semantic_search(
        user_input,
        top_k=top_k
    )

    # Best match
    best_result = results.iloc[0]

    score = float(best_result["similarity"])
    intent = best_result["intent"]
    response = best_result["response"]

    # Confidence / unknown-query check
    if score < threshold:

        return {
            "response": (
                "I'm sorry, but I couldn't find enough "
                "information to answer your question. "
                "Could you please rephrase your question?"
            ),
            "intent": "unknown",
            "score": score
        }

    return {
        "response": response,
        "intent": intent,
        "score": score
    }

In [ ]:
test_queries = [
    "Where is my order?",
    "My card payment was declined",
    "I want to return an item",
    "Where is my refund?",
    "I received the wrong product"
]

for query in test_queries:

    result = chatbot(query)

    print("\n" + "=" * 70)
    print("You:", query)
    print("Bot:", result["response"])
    print("Intent:", result["intent"])
    print("Similarity:", round(result["score"], 4))

======================================================================
You: Where is my order?
Bot: I'll do my best! I'd be happy to help you track your order. To check the status of your order, you can follow these steps:

1. Visit our website at {{Company Website URL}}.
2. Log in to your account using your registered email address and password.
3. Navigate to the "{{Order History}}" or "{{My Orders}}" section.
4. Look for the specific order you want to track and click on it.
5. You should be able to see the current status of your order, such as "Processing," "Shipped," or "Delivered," along with any tracking information available.

If you're unable to find the information you need or have any other questions, feel free to reach out to our customer support team at {{Customer Support Phone Number}} or via live chat on our website. We're here to assist you every step of the way!
Intent: track_order
Similarity: 0.9064

======================================================================
You: My card payment was declined
Bot: I'm sorry to hear that your card was declined and you're experiencing payment problems. I'll do my best to assist you with resolving this issue.

To report a payment problem, please follow these steps:

1. Double-check the card details: Ensure that the card number, expiration date, CVV, and billing address entered are correct. Sometimes, a small error can lead to a declined payment.

2. Verify sufficient funds: Make sure that you have enough funds available in your account to cover the transaction. Insufficient funds can result in a declined payment.

3. Contact your card issuer: If you've confirmed that the card details are accurate and you have enough funds, the next step is to reach out to your card issuer. They can provide insights into why the payment was declined and help resolve any issues.

4. Notify the merchant: If the payment was declined during a specific transaction, it's a good idea to contact the merchant directly. They may be able to provide further assistance or offer alternative payment methods.

5. Monitor your account: Keep an eye on your bank or credit card account to ensure that no unauthorized charges have been made.

If you continue to experience difficulties, please provide more specific information about the payment problem, such as the merchant's name, transaction details, or any error messages you encountered. This will help me assist you further.

Please remember that I'm here to support you throughout this process.
Intent: payment_issue
Similarity: 0.9039

======================================================================
You: I want to return an item
Bot: I'll make it happen! I'm here to assist you with that. Returning an item is a simple process. Here's what you need to do:

1. Visit our {{Returns & Exchanges}} page on our website.
2. Look for the option to initiate a return or exchange. It's usually labeled as "{{Start Return}}" or something similar.
3. Provide the requested information, such as your {{Order Number}} or {{Email Address}}, to locate your order.
4. Select the item you wish to return from your order.
5. Choose the reason for the return from the available options.
6. Follow the provided instructions to generate and print the return label.
7. Carefully package the item, including all original accessories and packaging.
8. Attach the return label to the package and make sure it's securely sealed.
9. Drop off the package at your nearest {{Carrier}} location or schedule a pickup.

Once we receive your returned item, we'll initiate the refund process. Please note that it may take some time for the refund to reflect on your original payment method.

If you have any specific questions or encounter any difficulties during the return process, don't hesitate to reach out to our {{Customer Support}} team. We're here to assist you every step of the way.
Intent: return_product
Similarity: 0.9706

======================================================================
You: Where is my refund?
Bot: I'm sorry to hear that you're looking for a refund. I can definitely assist you with that. Here's what you need to do to get a refund:

1. Contact our customer support team at {{Customer Support Phone Number}} or via email at {{Customer Support Email Address}}.
2. Explain the reason for your refund request and provide any necessary details such as your order number and purchase date.
3. Our customer support team will guide you through the refund process and assist you with the necessary steps.
4. Depending on the payment method you used for your purchase, the refund will be processed accordingly.
5. If you have any further questions or concerns regarding the refund, feel free to reach out to our customer support team.

We apologize for any inconvenience you may have experienced and appreciate your understanding.
Intent: request_refund
Similarity: 0.9023

======================================================================
You: I received the wrong product
Bot: I'm sorry to hear that you received the wrong product in your order. I completely understand how frustrating that can be. Let's get this sorted out for you. To resolve the issue, please follow these steps:

1. Take note of your {{Order Number}}. You may find it in your order confirmation email or on the packing slip.
2. Contact our customer support team through Live Chat on our website at {{Company Website URL}} or call {{Customer Support Phone Number}} during {{Customer Support Working Hours}}.
3. Provide them with your order number and explain the situation. Our team will guide you further to arrange for a return or exchange.
4. If necessary, they will assist you in arranging for a pickup of the wrong item and the delivery of the correct product.

We apologize for any inconvenience caused, and we'll do our best to rectify the situation promptly. If you have any other concerns or questions, please let me know.
Intent: wrong_item
Similarity: 0.8298

In [ ]:
query = "What is the weather today?"

result = chatbot(query)

print("You:", query)
print("Bot:", result["response"])
print("Intent:", result["intent"])
print("Similarity:", round(result["score"], 4))

You: What is the weather today?
Bot: I'm sorry, but I couldn't find enough information to answer your question. Could you please rephrase your question?
Intent: unknown
Similarity: 0.3829

In [ ]:
query = "Can you recommend a laptop for gaming?"

result = chatbot(query)

print("You:", query)
print("Bot:", result["response"])
print("Intent:", result["intent"])
print("Similarity:", round(result["score"], 4))

You: Can you recommend a laptop for gaming?
Bot: I'm sorry, but I couldn't find enough information to answer your question. Could you please rephrase your question?
Intent: unknown
Similarity: 0.2564

In [ ]:
print("*" * 70)
print("E-COMMERCE CUSTOMER SUPPORT CHATBOT")
print("*" * 70)

print("Type 'exit' to end the conversation.\n")

while True:

    user_input = input("You: ")

    if user_input.lower().strip() == "exit":

        print(
            "Bot: Thank you for using the "
            "E-commerce support assistant!"
        )
        break

    result = chatbot(user_input)

    print("\nBot:", result["response"])
    print("=" * 100)
    print()

**********************************************************************
E-COMMERCE CUSTOMER SUPPORT CHATBOT
**********************************************************************
Type 'exit' to end the conversation.

You: where is my order

Bot: I'll do my best! I'd be happy to help you track your order. To check the status of your order, you can follow these steps:

1. Visit our website at {{Company Website URL}}.
2. Log in to your account using your registered email address and password.
3. Navigate to the "{{Order History}}" or "{{My Orders}}" section.
4. Look for the specific order you want to track and click on it.
5. You should be able to see the current status of your order, such as "Processing," "Shipped," or "Delivered," along with any tracking information available.

If you're unable to find the information you need or have any other questions, feel free to reach out to our customer support team at {{Customer Support Phone Number}} or via live chat on our website. We're here to assist you every step of the way!
====================================================================================================

You: My card payment was declined

Bot: I'm sorry to hear that your card was declined and you're experiencing payment problems. I'll do my best to assist you with resolving this issue.

To report a payment problem, please follow these steps:

1. Double-check the card details: Ensure that the card number, expiration date, CVV, and billing address entered are correct. Sometimes, a small error can lead to a declined payment.

2. Verify sufficient funds: Make sure that you have enough funds available in your account to cover the transaction. Insufficient funds can result in a declined payment.

3. Contact your card issuer: If you've confirmed that the card details are accurate and you have enough funds, the next step is to reach out to your card issuer. They can provide insights into why the payment was declined and help resolve any issues.

4. Notify the merchant: If the payment was declined during a specific transaction, it's a good idea to contact the merchant directly. They may be able to provide further assistance or offer alternative payment methods.

5. Monitor your account: Keep an eye on your bank or credit card account to ensure that no unauthorized charges have been made.

If you continue to experience difficulties, please provide more specific information about the payment problem, such as the merchant's name, transaction details, or any error messages you encountered. This will help me assist you further.

Please remember that I'm here to support you throughout this process.
====================================================================================================

You: I want to return an item

Bot: I'll make it happen! I'm here to assist you with that. Returning an item is a simple process. Here's what you need to do:

1. Visit our {{Returns & Exchanges}} page on our website.
2. Look for the option to initiate a return or exchange. It's usually labeled as "{{Start Return}}" or something similar.
3. Provide the requested information, such as your {{Order Number}} or {{Email Address}}, to locate your order.
4. Select the item you wish to return from your order.
5. Choose the reason for the return from the available options.
6. Follow the provided instructions to generate and print the return label.
7. Carefully package the item, including all original accessories and packaging.
8. Attach the return label to the package and make sure it's securely sealed.
9. Drop off the package at your nearest {{Carrier}} location or schedule a pickup.

Once we receive your returned item, we'll initiate the refund process. Please note that it may take some time for the refund to reflect on your original payment method.

If you have any specific questions or encounter any difficulties during the return process, don't hesitate to reach out to our {{Customer Support}} team. We're here to assist you every step of the way.
====================================================================================================

You: Where is my refund?

Bot: I'm sorry to hear that you're looking for a refund. I can definitely assist you with that. Here's what you need to do to get a refund:

1. Contact our customer support team at {{Customer Support Phone Number}} or via email at {{Customer Support Email Address}}.
2. Explain the reason for your refund request and provide any necessary details such as your order number and purchase date.
3. Our customer support team will guide you through the refund process and assist you with the necessary steps.
4. Depending on the payment method you used for your purchase, the refund will be processed accordingly.
5. If you have any further questions or concerns regarding the refund, feel free to reach out to our customer support team.

We apologize for any inconvenience you may have experienced and appreciate your understanding.
====================================================================================================

You: I received the wrong product

Bot: I'm sorry to hear that you received the wrong product in your order. I completely understand how frustrating that can be. Let's get this sorted out for you. To resolve the issue, please follow these steps:

1. Take note of your {{Order Number}}. You may find it in your order confirmation email or on the packing slip.
2. Contact our customer support team through Live Chat on our website at {{Company Website URL}} or call {{Customer Support Phone Number}} during {{Customer Support Working Hours}}.
3. Provide them with your order number and explain the situation. Our team will guide you further to arrange for a return or exchange.
4. If necessary, they will assist you in arranging for a pickup of the wrong item and the delivery of the correct product.

We apologize for any inconvenience caused, and we'll do our best to rectify the situation promptly. If you have any other concerns or questions, please let me know.
====================================================================================================

You: When should my delivery arrive?

Bot: I appreciate your interest in knowing the delivery time for your order. I can definitely assist you with that.

To provide accurate information, I'll need the {{Order Number}} associated with your order. Could you please provide me with the order number?

Once I have the order number, I will be able to check the status and delivery time for your order. Rest assured, I'll do my best to provide you with the most up-to-date information.

Looking forward to your response!
====================================================================================================

You: few products ae missing

Bot: I'm sorry to hear that some of the products are missing from your order. I understand how frustrating that can be. Don't worry, I'm here to help you report it and get it sorted out. To report the missing items, please follow these steps:

1. Contact our customer support team at {{Customer Support Phone Number}} or send an email to {{Customer Support Email Address}}.
2. Provide them with your order number, which you can find in your order confirmation email or on your account page.
3. Let them know which specific products are missing from your order.

Our customer support team will investigate the issue and take the necessary steps to resolve it as quickly as possible. If you have any other questions or need further assistance, feel free to ask.
====================================================================================================

You: how to add product in a basket

Bot: Adding a product to your basket is quick and easy! Here's a step-by-step guide to help you:

1. Browse through our website and find the product you'd like to add.
2. Once you've found the product, click on the "Add to Basket" or "Add to Cart" button.
3. You can continue shopping and add more products to your basket, or proceed to checkout by clicking on the "Checkout" or "View Basket" button.
4. If you decide to continue shopping, repeat steps 1 and 2 for any additional products you want to add.
5. In the basket or cart page, review the products you've added and make any necessary changes, such as updating quantities or removing items.
6. When you're ready to complete your purchase, click on the "Checkout" button and follow the prompts to provide your shipping and payment details.

If you encounter any difficulties or have any questions along the way, feel free to reach out. Happy shopping!
====================================================================================================

You: The product arrived damaged

Bot: I'm really sorry to hear that the products you received were damaged. I understand how frustrating that can be. Please accept my sincerest apologies for any inconvenience caused. Rest assured, I'm here to help resolve this issue for you. To assist you further, I will need a few more details. Could you please provide me with your {{Order Number}} and describe the damage on the products? Once I have these details, I'll be able to take appropriate action and ensure that the matter is resolved to your satisfaction.
====================================================================================================

You: Can I exchange this product?

Bot: I'm happy to help! We're here to assist you with product exchanges. To get started, please provide us with a few details. Could you share your {{Order Number}} or the {{Product Name}} you would like to exchange? This will help us locate your order and guide you through the exchange process smoothly. We're committed to ensuring your satisfaction, so let's work together to find the best solution!
====================================================================================================

You: what's the weather today

Bot: I'm sorry, but I couldn't find enough information to answer your question. Could you please rephrase your question?
====================================================================================================

You: I want to cancel my order.

Bot: Of course, I'll assist you with canceling your order. I understand that sometimes circumstances change, and you may need to cancel a purchase. To proceed with the cancellation, please provide me with your {{Order Number}}. Once I have that information, I'll be able to assist you further and ensure the cancellation is processed smoothly.
====================================================================================================

You: I want to delete my account

Bot: I'm cognizant of the fact that you want to delete your account, and I'm here to assist you with that. I apologize if there's any dissatisfaction that led to this decision. To proceed with the account deletion, please follow these steps:

1. Log in to your account on our website.
2. Navigate to the account settings or profile section.
3. Look for the option to delete or close your account.
4. Follow the instructions provided to confirm the deletion.

Please note that deleting your account will permanently remove all your information and access to our services. If you have any remaining concerns or questions before proceeding, feel free to let me know.
====================================================================================================

You: how to check order history

Bot: Sure, I can help you with that! Checking your order history is easy. Just follow these steps:

1. Log in to your account on our website or app.
2. Go to your account dashboard or profile page.
3. Look for the "Order History" or "My Orders" section.
4. Click on it to view a list of your past orders.
5. You should see details like order numbers, dates, and order status.

If you need specific information about a particular order, like tracking details or invoices, you can click on the respective order for more details.

I hope this helps! If you have any further questions or need assistance with anything else, feel free to ask.
====================================================================================================

You: what is the shipping cost

Bot: I'll make it happen! I'd be more than happy to provide you with more information about the cost of shipping. The cost of shipping depends on several factors, such as the weight and dimensions of the package, the destination, and the shipping method you choose. To get an accurate estimate, I would recommend visiting our website and proceeding to the checkout page. There, you will be able to enter the necessary details, and our system will calculate the shipping cost for you. If you have any specific products or packages in mind, please let me know, and I can provide you with more tailored information.
====================================================================================================

You: can I talk to a human agent

Bot: Definitely! I understand that sometimes it's helpful to speak with a human agent directly, especially when you have specific concerns or questions. Our customer support team is always ready to assist you. Please hold on for a moment while I connect you to one of our live agents. They will provide you with the personalized assistance you need. Thank you for your patience!
====================================================================================================

You: how to get the invoice of my order

Bot: I'm sorry to hear that you didn't receive the invoice for your recent order. I understand how important it is to have a record of your purchase. Let me assist you with that. Here's what you can do to get a copy of your invoice:

1. Check your email: Please make sure to check your inbox, including spam or junk folders, for an email from us. The invoice might have been sent directly to your registered email address.

2. Account Dashboard: If you have an account with us, log in to your account and navigate to the "{{Order History}}" or "{{Purchase History}}" section. You should be able to find your order details and the option to download or print your invoice.

3. Contact Customer Support: If you've checked your email and account but still can't find the invoice, our dedicated customer support team is here to assist you. Reach out to them via {{Customer Support Phone Number}} or the Live Chat feature on our website at {{Company Website URL}}. They will be able to provide you with a digital copy of your invoice or assist you further.

Rest assured, we'll make sure you have access to your invoice promptly. Let me know if there's anything else I can assist you with!
====================================================================================================

You: what payment option do you have

Bot: Thank you for your interest in our payment options! I'll be glad to assist you with that. To view our payment options, please follow these simple steps:

1. Visit our {{Company Website}} and navigate to the "Payments" or "Payment Options" section.
2. Once on the payment options page, you will find a list of available payment methods we accept.
3. Take a look at the different payment methods, such as credit cards, debit cards, or digital wallets, and choose the one that suits you best.
4. If you need more details about any specific payment method or have any questions, feel free to reach out to our customer support team at {{Customer Support Phone Number}} or through the Live Chat on our website.

We strive to provide convenient and secure payment options to enhance your shopping experience. If you need any further assistance or have any other questions, please don't hesitate to let me know.
====================================================================================================

You: why my order has not arrived yet

Bot: I'm sorry to hear that you haven't received your order. Reporting a delivery issue is crucial to ensure that we can resolve this matter for you as quickly as possible. Let's get started on resolving this issue. Could you please provide me with your {{Order Number}}? With that information, I'll be able to investigate the status of your delivery and work towards finding a solution. Thank you for bringing this to our attention, and rest assured, we will do our utmost to assist you.
====================================================================================================

You: I got the incomplete order

Bot: I'm sorry to hear that there was an issue with your order. I appreciate you reaching out for assistance. I'll do my best to help you report the incomplete order and get this resolved for you. To report an incomplete order, please follow these steps:

1. Gather any relevant information you have about the order, such as the {{Order Number}}, {{Order Date}}, and the items that are missing.
2. Contact our customer support team through our {{Customer Support Channel}}. They will be able to assist you further and gather any necessary information to resolve the issue.
3. Explain the situation clearly to the customer support agent and provide them with the details of your incomplete order.
4. Our team will investigate the issue and work towards a resolution as soon as possible. They may request additional information or take steps to rectify the problem, such as arranging a replacement for the missing item.
5. Throughout the process, we'll keep you informed about the progress and any actions taken to resolve the incomplete order.

If you have any additional questions or concerns, please don't hesitate to let me know. We're here to help and ensure that you receive the complete order that you deserve.
====================================================================================================

You: exit
Bot: Thank you for using the E-commerce support assistant!

In [ ]:
import os

# Path to your ONNX model
model_path = onnx_model_path

# Get size
size_bytes = os.path.getsize(model_path)
size_mb = size_bytes / (1024 ** 2)
size_gb = size_bytes / (1024 ** 3)

print(f"ONNX model size: {size_mb:.2f} MB")
print(f"ONNX model size: {size_gb:.4f} GB")

# Check against 5 GB
if size_gb <= 5:
    print("✅ The ONNX model is below the 5 GB limit.")
else:
    print("❌ The ONNX model exceeds the 5 GB limit.")

ONNX model size: 86.26 MB
ONNX model size: 0.0842 GB
✅ The ONNX model is below the 5 GB limit.